### ISSUE TITLE
Minor Issues with New Landing Page

### ISSUE THREAD

**Issue by manassehkatz** [codidact/landing-page#31] opened 2020-01-30 05:48 UTC
1 - What does "focusing around the answer." mean? Might need to change the language to clarify.

2 - "big - and little questions" should probably be "big - and little - questions"

3 - The section with the announcements list signup ends up (on my screen anyway, but both Firefox & Chrome consistently) with the mailto link text split onto two lines - hyphenated. Source looks fine, it is simply a too-small box so it decides to split on the hyphen because there is one in a reasonable place. 

4 - Github logo in upper right is hard to see - light color on light background.

**Comment by ranolfi** [comment] 2020-01-30 06:13
@all: Item 4 addressed earlier 9417ca02 but still shows up incorrectly for @manassehkatz for some reason. We're trying to figure that out. Not a CDN issue, perhaps browser caching or something.

**Comment by manassehkatz** [comment] 2020-01-30 06:48
Tested via changing server index.html to point to logo-github-black.png and that works fine in all browsers/systems that I tried, as does the github staging page. Reverted change on server and goes back to previous inconsistent behavior. Suspect some sort of Cloudflare cachine problem.

**Comment by ranolfi** [comment] 2020-01-30 11:28
Be advised, item 4 seems to be [resolved](https://discordapp.com/channels/634104110131445811/635510793961472020/672336758314369034) for @manassehkatz. Most likely a caching issue indeed.

Items 1-3 still pending.

**Comment by manassehkatz** [comment] 2020-01-30 16:08
> Be advised, item 4 seems to be [resolved](https://discordapp.com/channels/634104110131445811/635510793961472020/672336758314369034) for @manassehkatz. Most likely a caching issue indeed.

Confirmed resolved.

**Comment by mattjbrent** [comment] 2020-02-25 02:24
Duplicate of #34 

These changes get resolved by changes in 34 which is pending MR merge.

**Closed by mattjbrent** 2020-02-25 02:24 UTC
Labels: area: frontend, meta: good first issue
