### ISSUE TITLE
First header doesn't show

### ISSUE THREAD

**Issue by galegosimpatico** [codidact/landing-page#55] opened 2020-08-23 00:45 UTC
**Describe the bug**
H1 tags don't show. DOM isn't honored and screenreaders and HTML parsers potentially show a different output than a _visual web browser_.

**To Reproduce**
N/A, discovered because of https://github.com/codidact/landing-page/pull/53 and demonstrated attaching pic in https://github.com/codidact/landing-page/pull/53#issuecomment-678713653. Contrast that vs pics https://user-images.githubusercontent.com/53513496/90967832-38371880-e4e5-11ea-8fbf-746cdbbe4dce.jpg and https://user-images.githubusercontent.com/53513496/90967836-4127ea00-e4e5-11ea-920b-17a21b6d8f0c.jpg of comment https://github.com/codidact/landing-page/pull/53#issuecomment-678711683 or vs pic https://user-images.githubusercontent.com/53513496/90967121-0d47c700-e4db-11ea-9573-dc0a62d8dcfc.png of https://github.com/codidact/landing-page/pull/53#issuecomment-678705362.

**Expected behavior**
H1 was printed on my Opera, like H2 and H3. **BTW H2 and H3 look the same**, would report that eventually. _In the "reader view available" of my phone it was printed as expected_.

**Screenshots**
Aye, see https://github.com/codidact/landing-page/pull/53#issuecomment-678713653 and pics https://user-images.githubusercontent.com/53513496/90967832-38371880-e4e5-11ea-8fbf-746cdbbe4dce.jpg and https://user-images.githubusercontent.com/53513496/90967836-4127ea00-e4e5-11ea-920b-17a21b6d8f0c.jpg of comment https://github.com/codidact/landing-page/pull/53#issuecomment-678711683 or vs pic https://user-images.githubusercontent.com/53513496/90967121-0d47c700-e4db-11ea-9573-dc0a62d8dcfc.png of https://github.com/codidact/landing-page/pull/53#issuecomment-678705362.

**Desktop:**
 - OS: macOS.
 - Browser: Opera.
 - Version: We don't really care for it is elementary DOM handling appealing to any browser and version.

**Smartphone:**
 - Device: iPhone 6.
 - OS: We don't care, we are discussing DOM visibility.
 - Browser: Safari "reader view available".
 - Version: We don't care, we are discussing DOM visibility.

**Comment by Daksh14** [comment] 2021-05-31 15:20
@galegosimpatico There has been a new iteration of the landing page, can you reproduce the error once again for it?

**Comment by galegosimpatico** [comment] 2021-05-31 16:58
I think this was an issue in classless headers being pasted to the page live (to the FAQ section), I suspect it'd still happen, but I don't know anymore if that's a real problem or not.

**Comment by galegosimpatico** [comment] 2021-05-31 17:00
I can't see any question pasted to the FAQ. There's no reason to work on this if there is no longer a FAQ.

**Comment by Daksh14** [comment] 2021-05-31 17:56
@galegosimpatico The new site can be accessed at  https://codidact.github.io/landing-page/ and there's been a re-design for the FAQ section. Can you check/validate if the problem is fixed

**Comment by galegosimpatico** [comment] 2021-05-31 20:06
> @galegosimpatico The new site can be accessed at https://codidact.github.io/landing-page/ and there's been a re-design for the FAQ section. [...]

Oh, that's a sweet redesign!

> [...] Can you check/validate if the problem is fixed

Do you add content live to that page? Because if not, or it gets added with styles, then this is #55 is no longer and issue and meets some immediate close.

**Comment by Daksh14** [comment] 2021-06-01 07:27
@galegosimpatico 
> Do you add content live to that page? Because if not, or it gets added with styles, then this is #55 is no longer an issue and meets some immediate close.

The FAQs are loaded from the resource https://raw.githubusercontent.com/codidact/docs/master/User-Help/CodidactMainPageFAQ.md and then parsed with js and is put into the respective layouts

**Comment by Daksh14** [comment] 2021-06-01 07:28
Fixed with new redesign #74

**Closed by Daksh14** 2021-06-01 07:28 UTC
